apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: default
data:
  53: "default/powerdns:533"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: default
data:
  53: "default/powerdns:533"
