kind: PersistentVolume
apiVersion: v1
metadata:
  name: powerdns-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/gqadonis/Projects/TribeHealth/ory/kratos/k8s/powerdns"
