# syntax = docker/dockerfile:1-experimental
FROM golang:1.17-alpine3.15 AS base

RUN apk -U --no-cache add build-base git gcc bash

WORKDIR /go/src/github.com/ory/kratos

ADD go.mod go.mod
ADD go.sum go.sum
ADD internal/httpclient/go.* internal/httpclient/

ENV GO111MODULE on
ENV CGO_ENABLED 1

RUN go mod download

ADD . .

ARG VERSION
ARG COMMIT
ARG BUILD_DATE

RUN go build -o /usr/bin/kratos main.go

FROM alpine:3.15.0

RUN apk add -U --no-cache ca-certificates
RUN apk --no-cache add curl

COPY --from=base /go/src/github.com/ory/kratos/cordico/certs/star_dev_cordico_com.crt /usr/local/share/ca-certificates
RUN cat /usr/local/share/ca-certificates/star_dev_cordico_com.crt >> /etc/ssl/certs/ca-certificates.crt

RUN addgroup -S ory; \
    adduser -S ory -G ory -D -u 10000 -h /home/ory -s /bin/nologin; \
    chown -R ory:ory /home/ory

COPY --from=base /usr/bin/kratos /usr/bin/kratos
COPY --from=base /go/src/github.com/ory/kratos/cordico/kratos.yml /etc/config/kratos.yml
COPY --from=base /go/src/github.com/ory/kratos/.schema /.schema

# Exposing the ory home directory to simplify passing in Kratos configuration (e.g. if the file $HOME/.kratos.yaml
# exists, it will be automatically used as the configuration file).
VOLUME /home/ory

# Declare the standard ports used by Kratos (4433 for public service endpoint, 4434 for admin service endpoint)
EXPOSE 4433 4434

USER 10000

ENTRYPOINT ["kratos"]
CMD ["serve", "-c", "/etc/config/kratos.yml", "--dev"]
